# Generated by Django 5.2.2 on 2025-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='queue_timestamp',
            field=models.DateTimeField(blank=True, help_text='Time patient was sent to clinician queue', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
