# Generated by Django 5.2.2 on 2025-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_queue_timestamp_alter_patient_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='counselling_queue_timestamp',
            field=models.DateTimeField(blank=True, help_text='Time patient was sent to counselling queue', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_queue_timestamp',
            field=models.DateTimeField(blank=True, help_text='Time patient was sent to laboratory queue', null=True),
        ),
    ]
